name: Deploy Hexo site to GitHub Pages

on:
  push:
    branches:
      - dev  # 监视的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # 指定Node.js版本

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Setup Hexo
        run: npm install hexo-cli -g

      - name: Generate static files
        run: hexo generate

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}  # 使用你在仓库秘密中添加的 MY_TOKEN
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          npx hexo deploy